PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS client;
CREATE TABLE client(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
    name VARCHAR(32)
);

DROP TABLE IF EXISTS category;
CREATE TABLE category(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
    name VARCHAR(32)
);

DROP TABLE IF EXISTS product;
CREATE TABLE product(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
    name VARCHAR(64),
    category VARCHAR(32),
    price INTEGER
);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;